# Generated by Django 3.0.5 on 2020-06-22 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_sportsnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
