# Generated by Django 3.0.5 on 2020-06-23 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 11, 19, 36, 529533, tzinfo=utc)),
        ),
    ]
