# Generated by Django 3.0.5 on 2020-07-06 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20200624_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='static/images/logo.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 16, 37, 19, 96604, tzinfo=utc)),
        ),
    ]
