# Generated by Django 3.0.5 on 2020-07-06 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20200706_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='documents/django archives/website/static/images', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 16, 45, 36, 876785, tzinfo=utc)),
        ),
    ]
