# Generated by Django 3.0.5 on 2020-07-08 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20200707_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 8, 18, 32, 10, 649740, tzinfo=utc)),
        ),
    ]
