# Generated by Django 3.0.5 on 2020-07-15 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_auto_20200711_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 16, 47, 22, 554989, tzinfo=utc)),
        ),
    ]
